### ISSUE TITLE
wdb40tool scan does not work when the SSID has space

### ISSUE THREAD

**Issue by wereHamster** [OnionIoT/wdb40#1]
The SSID of my home WLAN has a space (`X01-8 2.4Ghz`), and it seems that the `sscanf` in networkInfo::ParseNetworkFileLine trips over it. I did a quick test and `%s` only parses up to the first whitespace. I have not tried changing the SSID because I have too many devices connected to it at the moment.

This is a problem on my omega because now it won't automatically connect to the wwan. The problem started to appear after I upgraded to firmware 0.0.8.

**Comment by greenbreakfast** [comment]
Ok, I've made an update to the code, SSIDs with spaces work on my end.
Can you run `opkg upgrade wdb40` and then reboot and see if the connection works?

**Comment by wereHamster** [comment]
Can confirm that the device now successfully connects to my home wlan. Btw, I needed to run `opkg update` first, otherwise `opkg upgrade` didn't find any updates.

**Comment by greenbreakfast** [comment]
awesome, i'm glad it worked out
(yea i forgot to mention the `opkg update` command first, sorry)
