### ISSUE TITLE
Update to firmware 0.0.8 causes networks to become disabled by default

### ISSUE THREAD

**Issue by jakobwalowski** [OnionIoT/wdb40#3]
After a restart the /etc/config/wireless looks like this:

```
root@Omega-24A6:~# cat /etc/config/wireless                                                                          

config wifi-device 'radio0'
        option type 'mac80211'
        option hwmode '11g'
        option path 'platform/ar933x_wmac'
        option htmode 'HT20'
        option disabled '0'
        option channel '9'
        option txpower '30'
        option country 'US'

config wifi-iface
        option device 'radio0'
        option network 'wlan'
        option mode 'ap'
        option encryption 'none'
        option ssid 'Omega-24A6'

config wifi-iface
        option device 'radio0'
        option mode 'sta'
        option network 'wwan'
        option ssid 'MyNetworkname'                                                                                   
        option encryption 'psk2'                                                                                   
        option key 'A Password'
        option disabled '1'
```

then I have to connect to the omega either through the Omega-24A6 network or via serial interface, access the file and change the last line:
`option disabled '1'` to `option disabled '0'`.
Then the connection to the internet works. After another reboot the last line is back to `option disabled '1'`.

**Comment by greenbreakfast** [comment]
So on boot, wdb40 will disable all wifi networks (except the Omega's AP) and scan the local wifi networks looking for MyNetworkName, if it finds it, it will set disabled to 0.

Can you post the contents of `/tmp/wifi_config` and `/tmp/wifi_scan`? That will help narrow down the issue.

**Comment by jakobwalowski** [comment]
> ... scan the local wifi networks looking for MyNetworkName, if it finds it, it will set disabled to 0.

Does that mean, it is possible, that wdb40 does not find MyNetworkname?

Here are the files:

```
/tmp/wifi_config:
MyNetworkname:::: 3
```

```
/tmp/wifi_scan:
MyNetworkname:::: 3
otherNetwork:::: 1
anotherNetwork::::3
yetanotherNetwork::::3
Omega-1A2B::::1
```

**Comment by greenbreakfast** [comment]
Are those files modified? Can you post their original versions? They only show the SSID so no privacy concerns.

Can you also post the contents of `/tmp/wifi_match`?

**Comment by jakobwalowski** [comment]
```
root@Omega-24A6:~# cat /tmp/wifi_config
MyNetworkname :::: 3
root@Omega-24A6:~# cat /tmp/wifi_scan
Omega-0D9F :::: 1
MyNetworkname :::: 3
Telekom_FON :::: 1
Mizar :::: 3
```

Omega-0D9F is another onion omega
Telekom_FON and Mizar are my neighbors wifis.
There is no file `/tmp/wifi_match`

**Comment by greenbreakfast** [comment]
Is 'MyNetworkName' actually the name of your SSID? 

If not and your SSID name includes a **space**, try running the following:
`opkg update; opkg upgrade wdb40`
and then reboot. This should solve your problem.

If your SSID does not have a space:
Connect to your Omega via the serial terminal, run `wdb40 -v`, and post the output. We'll debug further.

**Comment by jakobwalowski** [comment]
Thank you very much! That was exactly it. Indeed my SSID includes a space. Sorry I did not spell it out, as I edited it out with the keys and stuck to it. Now I rebooted it several times and it works!

**Comment by greenbreakfast** [comment]
Awesome! Glad it works :)
Happy hacking
